### ISSUE TITLE
Serial MySensors gateway is polled too often?

### ISSUE THREAD

**Issue by flatsiedatsie** [tsathishkumar/MySController-rs#18]
To try something different I connected an Arduino Nano (FTDI) as a MySensors gateway.

This is the ini file:

`
[Gateway]
;type=TCP
;port=0.0.0.0:5003
type=SERIAL
port=/dev/ttyUSB0

[Controller]
type=TCP
port=0.0.0.0:9095
;type=SERIAL
;port=/dev/ttyUSB0

[Server]
database_url=/var/lib/myscontroller-rs/sqlite.db
`

This is the result:

Perhaps a speed issue?

pi@gateway:~/MySController-rs/target/debug $ sudo ./myscontroller-rs 
 INFO 2018-11-19T15:33:12Z: actix_web::server::srv: Starting 4 http workers
 INFO 2018-11-19T15:33:12Z: actix_web::server::srv: Starting server on http://0.0.0.0:8000
 INFO 2018-11-19T15:33:12Z: myscontroller_rs: Starting proxy server
 INFO 2018-11-19T15:33:12Z: myscontroller_rs::core::connection: Waiting for serial connection in -- /dev/ttyUSB0 ...
 INFO 2018-11-19T15:33:12Z: myscontroller_rs::core::connection: Server listening on -- 0.0.0.0:9095
 INFO 2018-11-19T15:33:12Z: myscontroller_rs::core::connection: Connected to -- /dev/ttyUSB0
 INFO 2018-11-19T15:33:12Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:12Z: myscontroller_rs::core::connection: Error while reading -- reached EOF
 INFO 2018-11-19T15:33:12Z: myscontroller_rs::core::connection: Waiting for serial connection in -- /dev/ttyUSB0 ...
ERROR 2018-11-19T15:33:12Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:12Z: myscontroller_rs::core::connection: Connected to -- /dev/ttyUSB0
 INFO 2018-11-19T15:33:12Z: actix_web::server::srv: Starting 4 http workers
 INFO 2018-11-19T15:33:12Z: actix_web::server::srv: Starting server on http://0.0.0.0:8888
 INFO 2018-11-19T15:33:13Z: actix_web::middleware::logger: 192.168.2.22:60912 [19/Nov/2018:16:33:13 +0100] "GET / HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" 0.002739
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "cc"
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "\u{c}s"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "!"
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "wA"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "x"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "2]"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "c`uf"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "\u{11}"
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "ca"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "\u{6}"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "hj"
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "c"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "u\u{15}N1B"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ")]"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "\r"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "5"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "("
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "a"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "qe"
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "\u{f}r:z"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "`c"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "q"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "p"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "`c"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "G"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "a"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "`u5Wr"
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:14Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:14Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "c"
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "2u\u{15}Dq"
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "a"
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "q"
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "F"
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:16Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "/O "
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-19T15:33:16Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:20Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
 INFO 2018-11-19T15:33:20Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:20Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:20Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:20Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:20Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-19T15:33:20Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-19T15:33:20Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""

**Comment by tsathishkumar** [comment]
I don't think the speed is an issue. The controller waits for a newline from the Serial Gateway. I see there are lot of empty lines. Could you monitor the serial output and see if it emits proper message?

**Comment by flatsiedatsie** [comment]
It does emit proper messages. But in minicom (serial monitor) I had to select "add newlines". I suspect MySensors doesn't add newlines, but uses something else. I'll check.

**Comment by tsathishkumar** [comment]
To be more specific, the controller reads until '\r'.  It could be related to speed as well. I'll have a l.

**Comment by tsathishkumar** [comment]
I checked the code now, I'm expecting new line only :)

```
match self.read(serial_buf.as_mut_slice()) {
                    Ok(_t) => {
                        let s = match str::from_utf8(&serial_buf) {
                            Ok(v) => v,
                            Err(_e) => break,
                        };
                        if s == "\u{0}" {
                            error!("Error while reading -- reached EOF");
                            broken_connection = true;
                            break;
                        }
                        line.push_str(&s);
                        if s.contains("\n") {
                            break;
                        }
                    }
                    Err(ref e) if e.kind() == io::ErrorKind::TimedOut => (),
                    Err(e) => {
                        error!("Error while reading -- {:?}", e);
                        broken_connection = true;
                        break;
                    }
                }
```

**Comment by tsathishkumar** [comment]
I checked the code of SerialPort crate. The default Baud rate is 9600. I'll add a feature to specify the baud rate when the connection is Serial type.

**Comment by tsathishkumar** [comment]
I have added feature to specify the baud_rate now. Can you set the right baud rate and test again if it works.

**Comment by flatsiedatsie** [comment]
Where can I change the baud rate? I don't see a commit that added this?

**Comment by tsathishkumar** [comment]
I forgot to push the changes. Now you can take a pull and you should be able to see the change in conf.ini file.

**Comment by flatsiedatsie** [comment]
Thanks.

I tried it, but no luck. I tested it, and the Arduino gateway is sending out data fine at 115200 baud.

This is the result:

```
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "e"
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "u"
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> ""
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
 INFO 2018-11-20T14:52:47Z: myscontroller_rs::core::connection: /dev/ttyUSB0 >> "8"
ERROR 2018-11-20T14:52:47Z: myscontroller_rs::core::interceptor: Error while parsing command message InvalidCommandMessage, simply forwarding to controller
```

**Comment by flatsiedatsie** [comment]
It is possible that the serial messages are not analysed? I see the messages coming by, but I don't see any response from MySController-rs?
