### ISSUE TITLE
Support for AirQuality Sensor

### ISSUE THREAD

**Issue by tsathishkumar** [tsathishkumar/MySController-rs#20]

**Comment by tsathishkumar** [comment]
@flatsiedatsie I have pushed the support for AirQuality sensor. Could you take a pull and test again and update if it works.

**Comment by flatsiedatsie** [comment]
I believe there are multiple types of air quality sensors.

**CO2**
For CO2 the level ranges between 0 (actually, 400 is the minimum you will ever get) and 5000. Some versions range between 0 and 2000.

http://www.aliexpress.com/item/1PCS-module-MH-Z19-infrared-co2-sensor-for-co2-monitor-Free-shipping/32371956420.html

**DUST**
Fine dust sensors measure dust in ug/m3 (microgram per meter squared), and range between 0.0 and 1000. They usually measure multiple 'buckets', such as particles with diameters of 1nm and 2.5nm and 10nm.

https://forum.mysensors.org/topic/6404/next-generation-dust-sensor-for-mysensors

**CO**
Carbon monoxide is measure in particles per million (ppm), ranging from 0 till 1500.

Often sensors will also output a text that translates the level into a human readable value. For example "safe" or "good". My devices do this for all air quality sensor types.

Here are some acceptable levels for carbon monoxide:
http://www.carbonmonoxidekills.com/are-you-at-risk/carbon-monoxide-levels/

**Other gasses**

Nitrogen dioxide NO2 0.05 – 10ppm
Ethanol C2H5OH 10 – 500ppm
Hydrogen H2 1 – 1000ppm
Ammonia NH3 1 – 500ppm
Methane CH4 >1000ppm
Propane C3H8 >1000ppm
Iso-butane C4H10 >1000ppm

volatile organic compounds are also popular to measure. These are, for example, released from paint and plastic.

**Comment by tsathishkumar** [comment]
Interesting, in the wot api it shows that the sensor is multi level. So ideally it should have values associated.
```
"@context": "https://iot.mozilla.org/schemas",
    "@type": [
      "multiLevelSensor"
    ],
    "actions": {},
    "description": "Air Quality sensor",
```

**Comment by tsathishkumar** [comment]
Is it still happening? Or can it be closed?
