### ISSUE TITLE
Data ending up at wrong device?

### ISSUE THREAD

**Issue by flatsiedatsie** [tsathishkumar/MySController-rs#25]
I just noticed something odd.

In the Mozilla interface, one of the locks on my smart lock got a multi-value option. I noticed that earlier and thought it was weird.

Now I noticed that it is showing the data from my CO2 sensor.

And looking closer:
- the temperature sensor is now a switch.
- the humidity sensor is now the temperature sensor

Could it be that everything has 'scooted over' now that the CO2 sensor gives data?

**Comment by tsathishkumar** [comment]
I'm closing it for now. Feel free to reopen if it happens again.
