### ISSUE TITLE
Strange data passed along to other optional controller?

### ISSUE THREAD

**Issue by flatsiedatsie** [tsathishkumar/MySController-rs#31]
I used the [controller] option to send the data along to Domoticz (fresh install). This is with an Ethernet gateway.

There I'm getting some.. odd things. Devices seem merged together there.

For example, suddenly it seems that I have a plant moisture sensor where the first two children (mostire sensors and dimmer) have both magically been turned into dust sensors. 

![irrigation-weird](https://user-images.githubusercontent.com/805405/49215378-90002880-f3c0-11e8-9d76-c4c98c95a5b1.png)
(normally this would be 6 moisture sensors and 6 dimmers).

Wait, it now also magically has a HVAC setpoint child :-D I'm not even sure where that came from, as I don't have any device connected currently that has a child like that.

![irrigation-weird-2](https://user-images.githubusercontent.com/805405/49215795-81664100-f3c1-11e8-8583-042ae297d695.png)

I have a similar weird issue with a dust sensor. It also suddenly has a HVAC setpoint setting.:

![setpoint-heat](https://user-images.githubusercontent.com/805405/49215414-a7d7ac80-f3c0-11e8-91de-336308f430c4.png)

The smart door lock has an "unknown!" child:

![doorlock](https://user-images.githubusercontent.com/805405/49215658-30564d00-f3c1-11e8-8f5f-a6bfe0677ff7.png)

Hmm, door 1 is now "eOor1". It might be a bad wireless connection.

Could it be caused by the two controllers trying to use the radio at the same time?

**Comment by flatsiedatsie** [comment]
Hmm, I now also see complete extra magic devices. That magical number 33 keeps popping up. 

The last two devices don't actually exist:

![extra-devices](https://user-images.githubusercontent.com/805405/49216527-377e5a80-f3c3-11e8-91cf-d819827a22b6.png)

The MySensors version reported in Domoticz is also strange. Instead of version 2.3 it says version 7896028 :-)

**Comment by flatsiedatsie** [comment]
I will test if it's not a hardware problem.

**Comment by tsathishkumar** [comment]
The controller functionality is a simple forward of what we get from Gateway. In fact MySController-rs doesn't send any extra message on it's own to the other controller. As you can see 

> INFO 2018-11-29T12:10:51Z: myscontroller_rs::core::connection: 0.0.0.0:5003 >> "0;255;3;0;22;13281070\n"

This is the message coming from Gateway. and the below subsequent message denotes that the same message forwarded to the controller connected through 8088.

So I think the Gateway is somehow sending wrong version, along with that some wrong sensor data.

**Comment by flatsiedatsie** [comment]
That's what I figured. But when it still happened with the other radio module I got confused.

Weirdness.
