### ISSUE TITLE
MySensors add-on

### ISSUE THREAD

**Issue by flatsiedatsie** [tsathishkumar/MySController-rs#40]
Just to let you know I've created an add-on for the Mozilla Webthing Gateway:
https://forum.mysensors.org/topic/10342/mozilla-webthings-mysensors-add-on-adapter

It might suit your needs too.

**Comment by tsathishkumar** [comment]
This is great news!! Thanks for the add-on. I tried to create the add-on on top this repo sometime back, but it wasn't straight forward. This looks great.
